apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: subscription-svc
  name: subscription-svc
  namespace: default
spec:
  serviceName: subscription-svc
  replicas: 1
  selector:
    matchLabels:
      app: subscription-svc
  template:
    metadata:
      labels:
        app: subscription-svc
    spec:
      containers:
        - name: subscription-svc
          image: subscription-svc:latest
          # remove for real clusters, useful for minikube
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
#              cpu: "250m"
            limits:
              memory: "576Mi"
#              cpu: "500m"
          readinessProbe:
            httpGet:
              path: "/ready"
              port: http
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: http
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 8010
              protocol: TCP
            - name: prometheus
              containerPort: 9080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_OPTS
              value: "-Xmx512m -Dconfig.resource=application-kube.conf"
            - name: KAFKA_URL
              value: "kafka-kafka-brokers:9092"
          volumeMounts:
            - name: subscription-svc-data
              mountPath: /kafka-streams
  volumeClaimTemplates:
    - metadata:
        name: subscription-svc-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscription-svc
  name: subscription-svc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
      nodePort: 30558
    - name: grpc
      protocol: TCP
      port: 8010
      targetPort: grpc
      nodePort: 30568
  selector:
    app: subscription-svc